# Generated by Django 5.2.7 on 2025-10-05 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.car'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.worker'),
        ),
    ]
