# Generated by Django 5.2.7 on 2025-10-05 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_car_is_available_worker_is_active_alter_sale_car_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='cost',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='car',
            name='potential_selling_price',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='car',
            name='year_production',
            field=models.IntegerField(max_length=4),
        ),
        migrations.AlterField(
            model_name='sale',
            name='selling_price',
            field=models.IntegerField(max_length=10),
        ),
    ]
