# Generated by Django 5.2.7 on 2025-10-05 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_car_cost_alter_car_potential_selling_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='employee',
            new_name='worker',
        ),
    ]
