# Generated by Django 5.2.7 on 2025-10-05 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_employee_sale_worker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='cost',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='car',
            name='potential_selling_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='car',
            name='year_production',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sale',
            name='selling_price',
            field=models.IntegerField(),
        ),
    ]
