# Generated by Django 5.2.7 on 2025-10-11 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_car_cost_alter_car_potential_selling_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='profit',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
